export const INIT = 'INIT';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_WINDOW_SIZE = 'UPDATE_WINDOW_SIZE';
export const UPDATE_PAGE_Y_OFFSET = 'UPDATE_PAGE_Y_OFFSET';
export const UPDATE_HANDLING_SIGN_IN = 'UPDATE_HANDLING_SIGN_IN';
export const UPDATE_STACKS_ACCESS = 'UPDATE_STACKS_ACCESS';
export const UPDATE_LIST_NAME = 'UPDATE_LIST_NAME';
export const UPDATE_NOTE_ID = 'UPDATE_NOTE_ID';
export const UPDATE_POPUP = 'UPDATE_POPUP';
export const UPDATE_SEARCH_STRING = 'UPDATE_SEARCH_STRING';
export const UPDATE_BULK_EDITING = 'UPDATE_BULK_EDITING';
export const UPDATE_EDITOR_FOCUSED = 'UPDATE_EDITOR_FOCUSED';
export const UPDATE_EDITOR_BUSY = 'UPDATE_EDITOR_BUSY';

export const ADD_SELECTED_NOTE_IDS = 'ADD_SELECTED_NOTE_IDS';
export const DELETE_SELECTED_NOTE_IDS = 'DELETE_SELECTED_NOTE_IDS';

export const FETCH = 'FETCH';
export const FETCH_COMMIT = 'FETCH_COMMIT';
export const FETCH_ROLLBACK = 'FETCH_ROLLBACK';

export const FETCH_MORE = 'FETCH_MORE';
export const FETCH_MORE_COMMIT = 'FETCH_MORE_COMMIT';
export const FETCH_MORE_ROLLBACK = 'FETCH_MORE_ROLLBACK';

export const ADD_NOTE = 'ADD_NOTE';
export const ADD_NOTE_COMMIT = 'ADD_NOTE_COMMIT';
export const ADD_NOTE_ROLLBACK = 'ADD_NOTE_ROLLBACK';

export const UPDATE_NOTE = 'UPDATE_NOTE';
export const UPDATE_NOTE_COMMIT = 'UPDATE_NOTE_COMMIT';
export const UPDATE_NOTE_ROLLBACK = 'UPDATE_NOTE_ROLLBACK';

export const MOVE_NOTES = 'MOVE_NOTES';
export const MOVE_NOTES_COMMIT = 'MOVE_NOTES_COMMIT';
export const MOVE_NOTES_ROLLBACK = 'MOVE_NOTES_ROLLBACK';

export const DELETE_NOTES = 'DELETE_NOTES';
export const DELETE_NOTES_COMMIT = 'DELETE_NOTES_COMMIT';
export const DELETE_NOTES_ROLLBACK = 'DELETE_NOTES_ROLLBACK';

export const CANCEL_DIED_NOTES = 'CANCEL_DIED_NOTES';

export const DELETE_OLD_NOTES_IN_TRASH = 'DELETE_OLD_NOTES_IN_TRASH';
export const DELETE_OLD_NOTES_IN_TRASH_COMMIT = 'DELETE_OLD_NOTES_IN_TRASH_COMMIT';
export const DELETE_OLD_NOTES_IN_TRASH_ROLLBACK = 'DELETE_OLD_NOTES_IN_TRASH_ROLLBACK';

export const MERGE_NOTES = 'MERGE_NOTES';
export const MERGE_NOTES_COMMIT = 'MERGE_NOTES_COMMIT';
export const MERGE_NOTES_ROLLBACK = 'MERGE_NOTES_ROLLBACK';

export const UPDATE_FETCHED_SETTINGS = 'UPDATE_FETCHED_SETTINGS';
export const UPDATE_LIST_NAME_EDITORS = 'UPDATE_LIST_NAME_EDITORS';

export const ADD_LIST_NAMES = 'ADD_LIST_NAMES';
export const UPDATE_LIST_NAMES = 'UPDATE_LIST_NAMES';
export const MOVE_LIST_NAME = 'MOVE_LIST_NAME';
export const MOVE_TO_LIST_NAME = 'MOVE_TO_LIST_NAME';
export const DELETE_LIST_NAMES = 'DELETE_LIST_NAMES';

export const UPDATE_SELECTING_LIST_NAME = 'UPDATE_SELECTING_LIST_NAME';
export const UPDATE_DELETING_LIST_NAME = 'UPDATE_DELETING_LIST_NAME';

export const UPDATE_DO_DELETE_OLD_NOTES_IN_TRASH = 'UPDATE_DO_DELETE_OLD_NOTES_IN_TRASH';
export const UPDATE_SORT_ON = 'UPDATE_SORT_ON';
export const UPDATE_DO_DESCENDING_ORDER = 'UPDATE_DO_DESCENDING_ORDER';
export const UPDATE_DO_ALERT_SCREEN_ROTATION = 'UPDATE_DO_ALERT_SCREEN_ROTATION';

export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const UPDATE_SETTINGS_COMMIT = 'UPDATE_SETTINGS_COMMIT';
export const UPDATE_SETTINGS_ROLLBACK = 'UPDATE_SETTINGS_ROLLBACK';

export const CANCEL_DIED_SETTINGS = 'CANCEL_DIED_SETTINGS';

export const UPDATE_DISCARD_ACTION = 'UPDATE_DISCARD_ACTION';

export const SYNC = 'SYNC';
export const SYNC_COMMIT = 'SYNC_COMMIT';
export const SYNC_ROLLBACK = 'SYNC_ROLLBACK';

export const UPDATE_SYNC_PROGRESS = 'UPDATE_SYNC_PROGRESS';
export const UPDATE_SYNCED = 'UPDATE_SYNCED';

export const INCREASE_SAVE_NOTE_COUNT = 'INCREASE_SAVE_NOTE_COUNT';
export const INCREASE_DISCARD_NOTE_COUNT = 'INCREASE_DISCARD_NOTE_COUNT';
export const INCREASE_UPDATE_NOTE_ID_URL_HASH_COUNT = 'INCREASE_UPDATE_NOTE_ID_URL_HASH_COUNT';
export const INCREASE_UPDATE_NOTE_ID_COUNT = 'INCREASE_UPDATE_NOTE_ID_COUNT';
export const INCREASE_CHANGE_LIST_NAME_COUNT = 'INCREASE_CHANGE_LIST_NAME_COUNT';
export const INCREASE_FOCUS_TITLE_COUNT = 'INCREASE_FOCUS_TITLE_COUNT';
export const INCREASE_SET_INIT_DATA_COUNT = 'INCREASE_SET_INIT_DATA_COUNT';
export const INCREASE_BLUR_COUNT = 'INCREASE_BLUR_COUNT';
export const INCREASE_UPDATE_EDITOR_WIDTH_COUNT = 'INCREASE_UPDATE_EDITOR_WIDTH_COUNT';
export const INCREASE_RESET_DID_CLICK_COUNT = 'INCREASE_RESET_DID_CLICK_COUNT';

export const ADD_SAVING_OBJ_URLS = 'ADD_SAVING_OBJ_URLS';
export const DELETE_SAVING_OBJ_URLS = 'DELETE_SAVING_OBJ_URLS';
export const CLEAR_SAVING_FPATHS = 'CLEAR_SAVING_FPATHS';
export const ADD_SAVING_FPATHS = 'ADD_SAVING_FPATHS';

export const UPDATE_EDITOR_SCROLL_ENABLED = 'UPDATE_EDITOR_SCROLL_ENABLED';

export const UPDATE_EDITING_NOTE = 'UPDATE_EDITING_NOTE';
export const UPDATE_EDITOR_UNMOUNT = 'UPDATE_EDITOR_UNMOUNT';
export const UPDATE_DID_DISCARD_EDITING = 'UPDATE_DID_DISCARD_EDITING';

export const UPDATE_IMPORT_ALL_DATA_PROGRESS = 'UPDATE_IMPORT_ALL_DATA_PROGRESS';
export const UPDATE_EXPORT_ALL_DATA_PROGRESS = 'UPDATE_EXPORT_ALL_DATA_PROGRESS';
export const UPDATE_DELETE_ALL_DATA_PROGRESS = 'UPDATE_DELETE_ALL_DATA_PROGRESS';

export const DELETE_ALL_DATA = 'DELETE_ALL_DATA';
export const RESET_STATE = 'RESET_STATE';
