export const INIT = 'INIT';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_WINDOW_SIZE = 'UPDATE_WINDOW_SIZE';
export const UPDATE_PAGE_Y_OFFSET = 'UPDATE_PAGE_Y_OFFSET';
export const UPDATE_HANDLING_SIGN_IN = 'UPDATE_HANDLING_SIGN_IN';

export const UPDATE_LIST_NAME = 'UPDATE_LIST_NAME';
export const UPDATE_NOTE_ID = 'UPDATE_NOTE_ID';
export const UPDATE_POPUP = 'UPDATE_POPUP';
export const UPDATE_EDITOR_FOCUSED = 'UPDATE_EDITOR_FOCUSED';
export const UPDATE_SEARCH_STRING = 'UPDATE_SEARCH_STRING';
export const UPDATE_BULK_EDITING = 'UPDATE_BULK_EDITING';

export const ADD_SELECTED_NOTE_IDS = 'ADD_SELECTED_NOTE_IDS';
export const DELETE_SELECTED_NOTE_IDS = 'DELETE_SELECTED_NOTE_IDS';
export const CLEAR_SELECTED_NOTE_IDS = 'CLEAR_SELECTED_NOTE_IDS';

export const DELETE_ALL_DATA = 'DELETE_ALL_DATA';
export const RESET_STATE = 'RESET_STATE';
