export const INIT = 'INIT';

export const UPDATE_HREF = 'UPDATE_HREF';
export const UPDATE_WINDOW_SIZE = 'UPDATE_WINDOW_SIZE';
export const UPDATE_HANDLING_SIGN_IN = 'UPDATE_HANDLING_SIGN_IN';
export const UPDATE_STACKS_ACCESS = 'UPDATE_STACKS_ACCESS';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_LIST_NAME = 'UPDATE_LIST_NAME';
export const UPDATE_NOTE_ID = 'UPDATE_NOTE_ID';
export const UPDATE_POPUP = 'UPDATE_POPUP';
export const UPDATE_SEARCH_STRING = 'UPDATE_SEARCH_STRING';
export const UPDATE_BULK_EDITING = 'UPDATE_BULK_EDITING';
export const UPDATE_EDITOR_FOCUSED = 'UPDATE_EDITOR_FOCUSED';
export const UPDATE_EDITOR_BUSY = 'UPDATE_EDITOR_BUSY';

export const ADD_SELECTED_NOTE_IDS = 'ADD_SELECTED_NOTE_IDS';
export const DELETE_SELECTED_NOTE_IDS = 'DELETE_SELECTED_NOTE_IDS';

export const FETCH = 'FETCH';
export const FETCH_COMMIT = 'FETCH_COMMIT';
export const FETCH_ROLLBACK = 'FETCH_ROLLBACK';

export const FETCH_MORE = 'FETCH_MORE';
export const FETCH_MORE_COMMIT = 'FETCH_MORE_COMMIT';
export const FETCH_MORE_ROLLBACK = 'FETCH_MORE_ROLLBACK';

export const CACHE_FETCHED_MORE = 'CACHE_FETCHED_MORE';
export const UPDATE_FETCHED_MORE = 'UPDATE_FETCHED_MORE';
export const CANCEL_FETCHED_MORE = 'CANCEL_FETCHED_MORE';

export const REFRESH_FETCHED = 'REFRESH_FETCHED';

export const ADD_NOTE = 'ADD_NOTE';
export const ADD_NOTE_COMMIT = 'ADD_NOTE_COMMIT';
export const ADD_NOTE_ROLLBACK = 'ADD_NOTE_ROLLBACK';

export const UPDATE_NOTE = 'UPDATE_NOTE';
export const UPDATE_NOTE_COMMIT = 'UPDATE_NOTE_COMMIT';
export const UPDATE_NOTE_ROLLBACK = 'UPDATE_NOTE_ROLLBACK';

export const MOVE_NOTES = 'MOVE_NOTES';
export const MOVE_NOTES_COMMIT = 'MOVE_NOTES_COMMIT';
export const MOVE_NOTES_ROLLBACK = 'MOVE_NOTES_ROLLBACK';

export const DELETE_NOTES = 'DELETE_NOTES';
export const DELETE_NOTES_COMMIT = 'DELETE_NOTES_COMMIT';
export const DELETE_NOTES_ROLLBACK = 'DELETE_NOTES_ROLLBACK';

export const CANCEL_DIED_NOTES = 'CANCEL_DIED_NOTES';

export const DELETE_OLD_NOTES_IN_TRASH = 'DELETE_OLD_NOTES_IN_TRASH';
export const DELETE_OLD_NOTES_IN_TRASH_COMMIT = 'DELETE_OLD_NOTES_IN_TRASH_COMMIT';
export const DELETE_OLD_NOTES_IN_TRASH_ROLLBACK = 'DELETE_OLD_NOTES_IN_TRASH_ROLLBACK';

export const MERGE_NOTES = 'MERGE_NOTES';
export const MERGE_NOTES_COMMIT = 'MERGE_NOTES_COMMIT';
export const MERGE_NOTES_ROLLBACK = 'MERGE_NOTES_ROLLBACK';

export const UPDATE_SELECTING_NOTE_ID = 'UPDATE_SELECTING_NOTE_ID';

export const UPDATE_LIST_NAME_EDITORS = 'UPDATE_LIST_NAME_EDITORS';

export const ADD_LIST_NAMES = 'ADD_LIST_NAMES';
export const UPDATE_LIST_NAMES = 'UPDATE_LIST_NAMES';
export const MOVE_LIST_NAME = 'MOVE_LIST_NAME';
export const MOVE_TO_LIST_NAME = 'MOVE_TO_LIST_NAME';
export const DELETE_LIST_NAMES = 'DELETE_LIST_NAMES';

export const UPDATE_SELECTING_LIST_NAME = 'UPDATE_SELECTING_LIST_NAME';
export const UPDATE_DELETING_LIST_NAME = 'UPDATE_DELETING_LIST_NAME';

export const UPDATE_DO_DELETE_OLD_NOTES_IN_TRASH = 'UPDATE_DO_DELETE_OLD_NOTES_IN_TRASH';
export const UPDATE_SORT_ON = 'UPDATE_SORT_ON';
export const UPDATE_DO_DESCENDING_ORDER = 'UPDATE_DO_DESCENDING_ORDER';
export const UPDATE_NOTE_DATE_SHOWING_MODE = 'UPDATE_NOTE_DATE_SHOWING_MODE';
export const UPDATE_NOTE_DATE_FORMAT = 'UPDATE_NOTE_DATE_FORMAT';
export const UPDATE_DO_SECTION_NOTES_BY_MONTH = 'UPDATE_DO_SECTION_NOTES_BY_MONTH';
export const UPDATE_DO_MORE_EDITOR_FONT_SIZES = 'UPDATE_MORE_EDITOR_FONT_SIZES';

export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const UPDATE_SETTINGS_COMMIT = 'UPDATE_SETTINGS_COMMIT';
export const UPDATE_SETTINGS_ROLLBACK = 'UPDATE_SETTINGS_ROLLBACK';

export const CANCEL_DIED_SETTINGS = 'CANCEL_DIED_SETTINGS';

export const UPDATE_MOVE_ACTION = 'UPDATE_MOVE_ACTION';
export const UPDATE_DELETE_ACTION = 'UPDATE_DELETE_ACTION';
export const UPDATE_DISCARD_ACTION = 'UPDATE_DISCARD_ACTION';

export const UPDATE_LIST_NAMES_MODE = 'UPDATE_LIST_NAMES_MODE';

export const SYNC = 'SYNC';
export const SYNC_COMMIT = 'SYNC_COMMIT';
export const SYNC_ROLLBACK = 'SYNC_ROLLBACK';

export const UPDATE_SYNC_PROGRESS = 'UPDATE_SYNC_PROGRESS';
export const UPDATE_SYNCED = 'UPDATE_SYNCED';

export const INCREASE_SAVE_NOTE_COUNT = 'INCREASE_SAVE_NOTE_COUNT';
export const INCREASE_DISCARD_NOTE_COUNT = 'INCREASE_DISCARD_NOTE_COUNT';
export const INCREASE_UPDATE_NOTE_ID_URL_HASH_COUNT = 'INCREASE_UPDATE_NOTE_ID_URL_HASH_COUNT';
export const INCREASE_UPDATE_NOTE_ID_COUNT = 'INCREASE_UPDATE_NOTE_ID_COUNT';
export const INCREASE_CHANGE_LIST_NAME_COUNT = 'INCREASE_CHANGE_LIST_NAME_COUNT';
export const INCREASE_FOCUS_TITLE_COUNT = 'INCREASE_FOCUS_TITLE_COUNT';
export const INCREASE_SET_INIT_DATA_COUNT = 'INCREASE_SET_INIT_DATA_COUNT';
export const INCREASE_BLUR_COUNT = 'INCREASE_BLUR_COUNT';
export const INCREASE_UPDATE_EDITOR_WIDTH_COUNT = 'INCREASE_UPDATE_EDITOR_WIDTH_COUNT';
export const INCREASE_RESET_DID_CLICK_COUNT = 'INCREASE_RESET_DID_CLICK_COUNT';
export const INCREASE_UPDATE_BULK_EDIT_URL_HASH_COUNT = 'INCREASE_UPDATE_BULK_EDIT_URL_HASH_COUNT';
export const INCREASE_UPDATE_BULK_EDIT_COUNT = 'INCREASE_UPDATE_BULK_EDIT_COUNT';
export const INCREASE_SHOW_NOTE_LIST_MENU_POPUP_COUNT = 'INCREASE_SHOW_NOTE_LIST_MENU_POPUP_COUNT';
export const INCREASE_SHOW_NLIM_POPUP_COUNT = 'INCREASE_SHOW_NLIM_POPUP_COUNT';

export const CLEAR_SAVING_FPATHS = 'CLEAR_SAVING_FPATHS';
export const ADD_SAVING_FPATHS = 'ADD_SAVING_FPATHS';

export const UPDATE_EDITOR_IS_UPLOADING = 'UPDATE_EDITOR_IS_UPLOADING';
export const UPDATE_EDITOR_SCROLL_ENABLED = 'UPDATE_EDITOR_SCROLL_ENABLED';

export const UPDATE_EDITING_NOTE = 'UPDATE_EDITING_NOTE';
export const UPDATE_EDITOR_UNMOUNT = 'UPDATE_EDITOR_UNMOUNT';
export const UPDATE_DID_DISCARD_EDITING = 'UPDATE_DID_DISCARD_EDITING';

export const UPDATE_SETTINGS_VIEW_ID = 'UPDATE_SETTINGS_VIEW_ID';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_COMMIT = 'GET_PRODUCTS_COMMIT';
export const GET_PRODUCTS_ROLLBACK = 'GET_PRODUCTS_ROLLBACK';

export const REQUEST_PURCHASE = 'REQUEST_PURCHASE';
export const REQUEST_PURCHASE_COMMIT = 'REQUEST_PURCHASE_COMMIT';
export const REQUEST_PURCHASE_ROLLBACK = 'REQUEST_PURCHASE_ROLLBACK';

export const RESTORE_PURCHASES = 'RESTORE_PURCHASES';
export const RESTORE_PURCHASES_COMMIT = 'RESTORE_PURCHASES_COMMIT';
export const RESTORE_PURCHASES_ROLLBACK = 'RESTORE_PURCHASES_ROLLBACK';

export const REFRESH_PURCHASES = 'REFRESH_PURCHASES';
export const REFRESH_PURCHASES_COMMIT = 'REFRESH_PURCHASES_COMMIT';
export const REFRESH_PURCHASES_ROLLBACK = 'REFRESH_PURCHASES_ROLLBACK';

export const UPDATE_IAP_PUBLIC_KEY = 'UPDATE_IAP_PUBLIC_KEY';
export const UPDATE_IAP_PRODUCT_STATUS = 'UPDATE_IAP_PRODUCT_STATUS';
export const UPDATE_IAP_PURCHASE_STATUS = 'UPDATE_IAP_PURCHASE_STATUS';
export const UPDATE_IAP_RESTORE_STATUS = 'UPDATE_IAP_RESTORE_STATUS';
export const UPDATE_IAP_REFRESH_STATUS = 'UPDATE_IAP_REFRESH_STATUS';

// Should end with 's', but keep them the same as in Brace.to!
export const PIN_NOTE = 'PIN_NOTE';
export const PIN_NOTE_COMMIT = 'PIN_NOTE_COMMIT';
export const PIN_NOTE_ROLLBACK = 'PIN_NOTE_ROLLBACK';

export const UNPIN_NOTE = 'UNPIN_NOTE';
export const UNPIN_NOTE_COMMIT = 'UNPIN_NOTE_COMMIT';
export const UNPIN_NOTE_ROLLBACK = 'UNPIN_NOTE_ROLLBACK';

export const MOVE_PINNED_NOTE = 'MOVE_PINNED_NOTE';
export const MOVE_PINNED_NOTE_COMMIT = 'MOVE_PINNED_NOTE_COMMIT';
export const MOVE_PINNED_NOTE_ROLLBACK = 'MOVE_PINNED_NOTE_ROLLBACK';

export const CANCEL_DIED_PINS = 'CANCEL_DIED_PINS';

export const UPDATE_SYSTEM_THEME_MODE = 'UPDATE_SYSTEM_THEME_MODE';
export const UPDATE_THEME = 'UPDATE_THEME';
export const UPDATE_UPDATING_THEME_MODE = 'UPDATE_UPDATING_THEME_MODE';
export const UPDATE_TIME_PICK = 'UPDATE_TIME_PICK';
export const UPDATE_IS_24H_FORMAT = 'UPDATE_IS_24H_FORMAT';

export const UPDATE_IMPORT_ALL_DATA_PROGRESS = 'UPDATE_IMPORT_ALL_DATA_PROGRESS';
export const UPDATE_EXPORT_ALL_DATA_PROGRESS = 'UPDATE_EXPORT_ALL_DATA_PROGRESS';
export const UPDATE_DELETE_ALL_DATA_PROGRESS = 'UPDATE_DELETE_ALL_DATA_PROGRESS';

export const DELETE_ALL_DATA = 'DELETE_ALL_DATA';
export const RESET_STATE = 'RESET_STATE';
