export const INIT = 'INIT';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_WINDOW_SIZE = 'UPDATE_WINDOW_SIZE';
export const UPDATE_PAGE_Y_OFFSET = 'UPDATE_PAGE_Y_OFFSET';
export const UPDATE_HANDLING_SIGN_IN = 'UPDATE_HANDLING_SIGN_IN';

export const DELETE_ALL_DATA = 'DELETE_ALL_DATA';
export const RESET_STATE = 'RESET_STATE';
