export const INIT = 'INIT';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_WINDOW_SIZE = 'UPDATE_WINDOW_SIZE';
export const UPDATE_PAGE_Y_OFFSET = 'UPDATE_PAGE_Y_OFFSET';
export const UPDATE_HANDLING_SIGN_IN = 'UPDATE_HANDLING_SIGN_IN';

export const UPDATE_LIST_NAME = 'UPDATE_LIST_NAME';
export const UPDATE_NOTE_ID = 'UPDATE_NOTE_ID';
export const UPDATE_POPUP = 'UPDATE_POPUP';
export const UPDATE_SEARCH_STRING = 'UPDATE_SEARCH_STRING';
export const UPDATE_BULK_EDITING = 'UPDATE_BULK_EDITING';
export const UPDATE_EDITOR_FOCUSED = 'UPDATE_EDITOR_FOCUSED';

export const ADD_SELECTED_NOTE_IDS = 'ADD_SELECTED_NOTE_IDS';
export const DELETE_SELECTED_NOTE_IDS = 'DELETE_SELECTED_NOTE_IDS';

export const FETCH = 'FETCH';
export const FETCH_COMMIT = 'FETCH_COMMIT';
export const FETCH_ROLLBACK = 'FETCH_ROLLBACK';

export const FETCH_MORE = 'FETCH_MORE';
export const FETCH_MORE_COMMIT = 'FETCH_MORE_COMMIT';
export const FETCH_MORE_ROLLBACK = 'FETCH_MORE_ROLLBACK';

export const ADD_NOTE = 'ADD_NOTE';
export const ADD_NOTE_COMMIT = 'ADD_NOTE_COMMIT';
export const ADD_NOTE_ROLLBACK = 'ADD_NOTE_ROLLBACK';

export const UPDATE_NOTE = 'UPDATE_NOTE';
export const UPDATE_NOTE_COMMIT = 'UPDATE_NOTE_COMMIT';
export const UPDATE_NOTE_ROLLBACK = 'UPDATE_NOTE_ROLLBACK';

export const MOVE_NOTES = 'MOVE_NOTES';
export const MOVE_NOTES_COMMIT = 'MOVE_NOTES_COMMIT';
export const MOVE_NOTES_ROLLBACK = 'MOVE_NOTES_ROLLBACK';

export const DELETE_NOTES = 'DELETE_NOTES';
export const DELETE_NOTES_COMMIT = 'DELETE_NOTES_COMMIT';
export const DELETE_NOTES_ROLLBACK = 'DELETE_NOTES_ROLLBACK';

export const CANCEL_DIED_NOTES = 'CANCEL_DIED_NOTES';

export const DELETE_OLD_NOTES_IN_TRASH = 'DELETE_OLD_NOTES_IN_TRASH';
export const DELETE_OLD_NOTES_IN_TRASH_COMMIT = 'DELETE_OLD_NOTES_IN_TRASH_COMMIT';
export const DELETE_OLD_NOTES_IN_TRASH_ROLLBACK = 'DELETE_OLD_NOTES_IN_TRASH_ROLLBACK';

export const MERGE_NOTES = 'MERGE_NOTES';
export const MERGE_NOTES_COMMIT = 'MERGE_NOTES_COMMIT';
export const MERGE_NOTES_ROLLBACK = 'MERGE_NOTES_ROLLBACK';

export const ADD_LIST_NAMES = 'ADD_LIST_NAMES';
export const ADD_LIST_NAMES_COMMIT = 'ADD_LIST_NAMES_COMMIT';
export const ADD_LIST_NAMES_ROLLBACK = 'ADD_LIST_NAMES_ROLLBACK';

export const UPDATE_LIST_NAMES = 'UPDATE_LIST_NAMES';
export const UPDATE_LIST_NAMES_COMMIT = 'UPDATE_LIST_NAMES_COMMIT';
export const UPDATE_LIST_NAMES_ROLLBACK = 'UPDATE_LIST_NAMES_ROLLBACK';

export const MOVE_LIST_NAME = 'MOVE_LIST_NAME';
export const MOVE_LIST_NAME_COMMIT = 'MOVE_LIST_NAME_COMMIT';
export const MOVE_LIST_NAME_ROLLBACK = 'MOVE_LIST_NAME_ROLLBACK';

export const DELETE_LIST_NAMES = 'DELETE_LIST_NAMES';
export const DELETE_LIST_NAMES_COMMIT = 'DELETE_LIST_NAMES_COMMIT';
export const DELETE_LIST_NAMES_ROLLBACK = 'DELETE_LIST_NAMES_ROLLBACK';

export const UPDATE_DELETING_LIST_NAME = 'UPDATE_DELETING_LIST_NAME';

export const RETRY_ADD_LIST_NAMES = 'RETRY_ADD_LIST_NAMES';
export const RETRY_UPDATE_LIST_NAMES = 'RETRY_UPDATE_LIST_NAMES';
export const RETRY_MOVE_LIST_NAME = 'RETRY_MOVE_LIST_NAME';
export const RETRY_DELETE_LIST_NAMES = 'RETRY_DELETE_LIST_NAMES';

export const CANCEL_DIED_LIST_NAMES = 'CANCEL_DIED_LIST_NAMES';

export const UPDATE_DISCARD_ACTION = 'UPDATE_DISCARD_ACTION';

export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const UPDATE_SETTINGS_COMMIT = 'UPDATE_SETTINGS_COMMIT';
export const UPDATE_SETTINGS_ROLLBACK = 'UPDATE_SETTINGS_ROLLBACK';

export const UPDATE_UPDATE_SETTINGS_PROGRESS = 'UPDATE_UPDATE_SETTINGS_PROGRESS';

export const SYNC = 'SYNC';
export const SYNC_COMMIT = 'SYNC_COMMIT';
export const SYNC_ROLLBACK = 'SYNC_ROLLBACK';

export const UPDATE_SYNC_PROGRESS = 'UPDATE_SYNC_PROGRESS';
export const UPDATE_SYNCED = 'UPDATE_SYNCED';

export const INCREASE_SAVE_NOTE_COUNT = 'INCREASE_SAVE_NOTE_COUNT';
export const INCREASE_DISCARD_NOTE_COUNT = 'INCREASE_DISCARD_NOTE_COUNT';
export const INCREASE_CONFIRM_DISCARD_NOTE_COUNT = 'INCREASE_CONFIRM_DISCARD_NOTE_COUNT';
export const INCREASE_UPDATE_NOTE_ID_URL_HASH_COUNT = 'INCREASE_UPDATE_NOTE_ID_URL_HASH_COUNT';
export const INCREASE_UPDATE_NOTE_ID_COUNT = 'INCREASE_UPDATE_NOTE_ID_COUNT';
export const INCREASE_CHANGE_LIST_NAME_COUNT = 'INCREASE_CHANGE_LIST_NAME_COUNT';
export const INCREASE_UPDATE_EDITOR_WIDTH_COUNT = 'INCREASE_UPDATE_EDITOR_WIDTH_COUNT';

export const UPDATE_EXPORT_ALL_DATA_PROGRESS = 'UPDATE_EXPORT_ALL_DATA_PROGRESS';
export const UPDATE_DELETE_ALL_DATA_PROGRESS = 'UPDATE_DELETE_ALL_DATA_PROGRESS';

export const DELETE_ALL_DATA = 'DELETE_ALL_DATA';
export const RESET_STATE = 'RESET_STATE';
